#
# Module manifest for module 'NewManifest'
#
# Generated by: Jared Atkinson
#
# Generated on: 1/10/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WmiEvent'

# Version number of this module.
ModuleVersion = '1.0.1'

# ID used to uniquely identify this module
GUID = 'd8ddd5f6-ba6d-4f98-9a62-6d5d96fcc619'

# Author of this module
Author = 'Jared Atkinson'

# Company or vendor of this module
CompanyName = 'PowerShell Mafia'

# Copyright statement for this module
Copyright = '(c) 2016 Jared Atkinson. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module to abstract the complexities of Permanent WMI Event Subscriptions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'cdxml\ActiveScriptEventConsumer.cdxml', 
    'cdxml\CommandLineEventConsumer.cdxml', 
    'cdxml\LogFileEventConsumer.cdxml', 
    'cdxml\NtEventLogEventConsumer.cdxml', 
    'cdxml\SmtpEventConsumer.cdxml', 
    'cdxml\WmiEventSubscription.cdxml', 
    'cdxml\WmiEventConsumer.cdxml', 
    'cdxml\WmiEventFilter.cdxml'
)

# Functions to export from this module
FunctionsToExport = @(
    'Get-ActiveScriptEventConsumer'
    'Get-CommandLineEventConsumer'
    'Get-LogFileEventConsumer'
    'Get-NtEventLogEventConsumer'
    'Get-SmtpEventConsumer'
    'Get-WmiEventConsumer'
    'Get-WmiEventFilter'
    'Get-WmiEventSubscription'
    'New-ActiveScriptEventConsumer'
    'New-CommandLineEventConsumer'
    'New-LogFileEventConsumer'
    'New-NtEventLogEventConsumer'
    'New-SmtpEventConsumer'
    'New-WmiEventConsumer'
    'New-WmiEventFilter'
    'New-WmiEventSubscription'
    'New-CimSessionDcom'
    'Register-PermanentWmiEvent'
)
        

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'WMIPermanentEvents','Eventing','EventMonitoring','WMI'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Invoke-IR/WmiEvent/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Invoke-IR/WmiEvent'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @"
- Added ComputerName and Crendential parameters to all cmdlets
"@


        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

